# Generated by Django 4.0 on 2022-01-15 04:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='remains',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
