# Generated by Django 4.0 on 2022-01-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
